version: "3.3"
services:
  face_recognition_service:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    image: face_recognition_service
    container_name: face_recognition_service
    restart: on-failure
    command: bash -c "pip3 install cmake && pip3 install -r requirements.txt && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8101"
    ports:
      - "8101:8101"
