# Generated by Django 4.1.6 on 2024-05-02 12:20

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by', models.PositiveIntegerField(default=None, null=True)),
                ('image', models.ImageField(upload_to=api.models.imagedir, verbose_name='Images|Фотография')),
                ('trained', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At|Создано')),
                ('person_id', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by', models.PositiveIntegerField(default=None, null=True)),
                ('image', models.ImageField(upload_to=api.models.imagedir, verbose_name='Images|Фотография')),
                ('trained', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At|Создано')),
                ('person_id', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
